// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// simulate_nROUSE
Rcpp::List simulate_nROUSE(Rcpp::NumericVector presentations, Rcpp::NumericVector primeInput, Rcpp::NumericVector param);
RcppExport SEXP nROUSE_simulate_nROUSE(SEXP presentationsSEXP, SEXP primeInputSEXP, SEXP paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type presentations(presentationsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type primeInput(primeInputSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type param(paramSEXP);
    __result = Rcpp::wrap(simulate_nROUSE(presentations, primeInput, param));
    return __result;
END_RCPP
}
