// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// simulate_nROUSE
Rcpp::List simulate_nROUSE(Rcpp::NumericVector presentations, Rcpp::NumericVector primeInput, Rcpp::NumericVector param);
RcppExport SEXP _nROUSE_simulate_nROUSE(SEXP presentationsSEXP, SEXP primeInputSEXP, SEXP paramSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type presentations(presentationsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type primeInput(primeInputSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type param(paramSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_nROUSE(presentations, primeInput, param));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nROUSE_simulate_nROUSE", (DL_FUNC) &_nROUSE_simulate_nROUSE, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_nROUSE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
