# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib nROUSE
#' @importFrom Rcpp sourceCpp
NULL

#' The nROUSE model
#'
#' Function to simulate the predictions of the nROUSE model (Huber 
#' and O'Reilly, 2003) for perceptual identification latencies 
#' and forced-choice accuracy.
#'
#' @param presentations A vector giving the duration (in ms) of 
#'   the prime, the target, the mask, and the choice alternatives.
#' @param primeInput A vector of two elements used to set the type 
#'   of prime. For instance, [2,0] indicates a double prime for 
#'   targets, while [0,1] indicates a single prime for foils.
#' @param param A vector giving the values for the parameters.
#'  \describe{
#'    \item{\code{param[1]}}{Semantic to orthographic feedback scalar}
#'    \item{\code{param[2]}}{Noise constant}
#'    \item{\code{param[3]}}{Constant leak current}
#'    \item{\code{param[4]}}{Synaptic depletion rate}
#'    \item{\code{param[5]}}{Recovery rate}
#'    \item{\code{param[6]}}{Inhibition constant}
#'    \item{\code{param[7]}}{Activation threshold}
#'    \item{\code{param[8]}}{Temporal attention}
#'    \item{\code{param[9]}}{Integration time constant (Visual)}
#'    \item{\code{param[10]}}{Integration time constant (Orthographic)}
#'    \item{\code{param[10]}}{Integration time constant (Semantic)}
#'     }
#'
#' @section References:
#' Huber, D. E., & O'Reilly, R. C. (2003). Persistence and 
#'   accommodation in short-term priming and other perceptual 
#'   paradigms: Temporal segregation through synaptic depression. 
#'   Cognitive Science, 27(3), 403-430.
#'
#' @examples
#' # Define duration (in ms) for prime, target, mask, and choices
#' presentations = c( 17, 50, 450, 500 )
#' # Set a double prime for targets
#' primeInput = c(2,0)
#' # Simulate model with default parameters
#' sim = simulate_nROUSE( presentations, primeInput )
#'
#' @export
simulate_nROUSE <- function(presentations, primeInput, param = as.numeric( c(                                 .25, .0302, .15, .324, .022,                                  .9844, .15, 1.0, .0294, .0609,                                  .015 ))) {
    .Call('nROUSE_simulate_nROUSE', PACKAGE = 'nROUSE', presentations, primeInput, param)
}

